limit = 10000
log_lines = 25

input = '''
'''

[expected]
stdout = '''
Hello, World!
ticks: 618
'''
code_hex = '''
0 - 20003C - CALL 60
3 - 00 - HALT
4 - 01 - DUP
5 - 05 - LOAD
6 - 03 - SWAP
7 - 2100000001 - PUSHI32 1
12 - 07 - ADD
13 - 03 - SWAP
14 - 2100000000 - PUSHI32 0
19 - 04 - OVER
20 - 04 - OVER
21 - 03 - SWAP
22 - 0D - LT
23 - 1F0021 - JZ 33
26 - 03 - SWAP
27 - 14 - TOR
28 - 14 - TOR
29 - 01 - DUP
30 - 16 - RPEEK
31 - 07 - ADD
32 - 05 - LOAD
33 - 1BFF02 - STOREA 0xFF02
36 - 15 - FROMR
37 - 2100000001 - PUSHI32 1
42 - 07 - ADD
43 - 01 - DUP
44 - 16 - RPEEK
45 - 0D - LT
46 - 1F0004 - JZ 4
49 - 14 - TOR
50 - 1EFFE8 - JMP -24
53 - 02 - DROP
54 - 15 - FROMR
55 - 02 - DROP
56 - 1E0002 - JMP 2
59 - 02 - DROP
60 - 02 - DROP
61 - 02 - DROP
62 - 12 - RET
63 - 2100000001 - PUSHI32 1
68 - 20FFBD - CALL -67
71 - 12 - RET'''
data_hex = '''
0 - 00000000 - 0
1 - 0000000D - 13
2 - 00000048 - 72
3 - 00000065 - 101
4 - 0000006C - 108
5 - 0000006C - 108
6 - 0000006F - 111
7 - 0000002C - 44
8 - 00000020 - 32
9 - 00000057 - 87
10 - 0000006F - 111
11 - 00000072 - 114
12 - 0000006C - 108
13 - 00000064 - 100
14 - 00000021 - 33'''
interrupts = '''
'''
log_head = '''
tick=00001 state=FETCH_OPCODE         pc=0001 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- instr_addr=0
tick=00002 state=FETCH_ARGUMENT       pc=0003 ir=CALL    arg=         60 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- CALL 60
tick=00003 state=EXECUTE              pc=003F ir=CALL    arg=         60 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- CALL
tick=00004 state=FETCH_OPCODE         pc=0040 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=63
tick=00005 state=FETCH_ARGUMENT       pc=0044 ir=PUSHI32 arg=          1 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00006 state=EXECUTE              pc=0044 ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00007 state=FETCH_OPCODE         pc=0045 ir=CALL    arg=          0 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=68
tick=00008 state=FETCH_ARGUMENT       pc=0047 ir=CALL    arg=        -67 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- CALL -67
tick=00009 state=EXECUTE              pc=0004 ir=CALL    arg=        -67 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- CALL
tick=00010 state=FETCH_OPCODE         pc=0005 ir=DUP     arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- instr_addr=4
tick=00011 state=FETCH_ARGUMENT       pc=0005 ir=DUP     arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- DUP
tick=00012 state=EXECUTE              pc=0005 ir=DUP     arg=          0 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- DUP
tick=00013 state=FETCH_OPCODE         pc=0006 ir=LOAD    arg=          0 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=5
tick=00014 state=FETCH_ARGUMENT       pc=0006 ir=LOAD    arg=          0 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- LOAD
tick=00015 state=EXECUTE              pc=0006 ir=LOAD    arg=          0 tos=         13 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- LOAD
tick=00016 state=FETCH_OPCODE         pc=0007 ir=SWAP    arg=          0 tos=         13 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=6
tick=00017 state=FETCH_ARGUMENT       pc=0007 ir=SWAP    arg=          0 tos=         13 nos=          1 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00018 state=EXECUTE              pc=0007 ir=SWAP    arg=          0 tos=          1 nos=         13 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00019 state=FETCH_OPCODE         pc=0008 ir=PUSHI32 arg=          0 tos=          1 nos=         13 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=7
tick=00020 state=FETCH_ARGUMENT       pc=000C ir=PUSHI32 arg=          1 tos=          1 nos=         13 sp=D001 rp=E001 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00021 state=EXECUTE              pc=000C ir=PUSHI32 arg=          1 tos=          1 nos=          1 sp=D002 rp=E001 flags=zncvieint mode=main input=-- PUSHI32
tick=00022 state=FETCH_OPCODE         pc=000D ir=ADD     arg=          0 tos=          1 nos=          1 sp=D002 rp=E001 flags=zncvieint mode=main input=-- instr_addr=12
tick=00023 state=FETCH_ARGUMENT       pc=000D ir=ADD     arg=          0 tos=          1 nos=          1 sp=D002 rp=E001 flags=zncvieint mode=main input=-- ADD
tick=00024 state=EXECUTE              pc=000D ir=ADD     arg=          0 tos=          2 nos=         13 sp=D001 rp=E001 flags=zncvieint mode=main input=-- ADD
tick=00025 state=FETCH_OPCODE         pc=000E ir=SWAP    arg=          0 tos=          2 nos=         13 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=13
'''
