limit = 5000
log_lines = 50

input = '''
80 A
130 l
180 i
230 c
280 e
330 \n
'''

[expected]
stdout = '''
What is your name?
Hello, Alice!

ticks: 1914
'''
code_hex = '''
0 - 2000D2 - CALL 210
3 - 00 - HALT
4 - 01 - DUP
5 - 05 - LOAD
6 - 03 - SWAP
7 - 2100000001 - PUSHI32 1
12 - 07 - ADD
13 - 03 - SWAP
14 - 2100000000 - PUSHI32 0
19 - 04 - OVER
20 - 04 - OVER
21 - 03 - SWAP
22 - 0D - LT
23 - 1F0021 - JZ 33
26 - 03 - SWAP
27 - 14 - TOR
28 - 14 - TOR
29 - 01 - DUP
30 - 16 - RPEEK
31 - 07 - ADD
32 - 05 - LOAD
33 - 1BFF02 - STOREA 0xFF02
36 - 15 - FROMR
37 - 2100000001 - PUSHI32 1
42 - 07 - ADD
43 - 01 - DUP
44 - 16 - RPEEK
45 - 0D - LT
46 - 1F0004 - JZ 4
49 - 14 - TOR
50 - 1EFFE8 - JMP -24
53 - 02 - DROP
54 - 15 - FROMR
55 - 02 - DROP
56 - 1E0002 - JMP 2
59 - 02 - DROP
60 - 02 - DROP
61 - 02 - DROP
62 - 12 - RET
63 - 2100000001 - PUSHI32 1
68 - 05 - LOAD
69 - 2100000001 - PUSHI32 1
74 - 07 - ADD
75 - 2100000002 - PUSHI32 2
80 - 05 - LOAD
81 - 2100000000 - PUSHI32 0
86 - 04 - OVER
87 - 04 - OVER
88 - 03 - SWAP
89 - 0D - LT
90 - 1F0021 - JZ 33
93 - 03 - SWAP
94 - 14 - TOR
95 - 14 - TOR
96 - 01 - DUP
97 - 16 - RPEEK
98 - 07 - ADD
99 - 05 - LOAD
100 - 1BFF02 - STOREA 0xFF02
103 - 15 - FROMR
104 - 2100000001 - PUSHI32 1
109 - 07 - ADD
110 - 01 - DUP
111 - 16 - RPEEK
112 - 0D - LT
113 - 1F0004 - JZ 4
116 - 14 - TOR
117 - 1EFFE8 - JMP -24
120 - 02 - DROP
121 - 15 - FROMR
122 - 02 - DROP
123 - 1E0002 - JMP 2
126 - 02 - DROP
127 - 02 - DROP
128 - 02 - DROP
129 - 12 - RET
130 - 1AFF00 - LOADA 0xFF00
133 - 2100000004 - PUSHI32 4
138 - 06 - STORE
139 - 2100000004 - PUSHI32 4
144 - 05 - LOAD
145 - 210000000A - PUSHI32 10
150 - 0C - EQ
151 - 1F000E - JZ 14
154 - 2100000001 - PUSHI32 1
159 - 2100000003 - PUSHI32 3
164 - 06 - STORE
165 - 1E002C - JMP 44
168 - 2100000004 - PUSHI32 4
173 - 05 - LOAD
174 - 2100000001 - PUSHI32 1
179 - 05 - LOAD
180 - 2100000001 - PUSHI32 1
185 - 07 - ADD
186 - 2100000002 - PUSHI32 2
191 - 05 - LOAD
192 - 07 - ADD
193 - 06 - STORE
194 - 2100000002 - PUSHI32 2
199 - 05 - LOAD
200 - 2100000001 - PUSHI32 1
205 - 07 - ADD
206 - 2100000002 - PUSHI32 2
211 - 06 - STORE
212 - 19 - IRET
213 - 2100000005 - PUSHI32 5
218 - 2100000001 - PUSHI32 1
223 - 06 - STORE
224 - 210000000B - PUSHI32 11
229 - 20FF1C - CALL -228
232 - 210000000A - PUSHI32 10
237 - 1BFF02 - STOREA 0xFF02
240 - 17 - EI
241 - 2100000003 - PUSHI32 3
246 - 05 - LOAD
247 - 1FFFF7 - JZ -9
250 - 210000001E - PUSHI32 30
255 - 20FF02 - CALL -254
258 - 20FF3A - CALL -198
261 - 2100000021 - PUSHI32 33
266 - 1BFF02 - STOREA 0xFF02
269 - 210000000A - PUSHI32 10
274 - 1BFF02 - STOREA 0xFF02
277 - 12 - RET'''
data_hex = '''
0 - 00000000 - 0
1 - 00000000 - 0
2 - 00000000 - 0
3 - 00000000 - 0
4 - 00000000 - 0
5 - 00000005 - 5
6 - 0000003F - 63
7 - 0000003F - 63
8 - 0000003F - 63
9 - 0000003F - 63
10 - 0000003F - 63
11 - 00000012 - 18
12 - 00000057 - 87
13 - 00000068 - 104
14 - 00000061 - 97
15 - 00000074 - 116
16 - 00000020 - 32
17 - 00000069 - 105
18 - 00000073 - 115
19 - 00000020 - 32
20 - 00000079 - 121
21 - 0000006F - 111
22 - 00000075 - 117
23 - 00000072 - 114
24 - 00000020 - 32
25 - 0000006E - 110
26 - 00000061 - 97
27 - 0000006D - 109
28 - 00000065 - 101
29 - 0000003F - 63
30 - 00000007 - 7
31 - 00000048 - 72
32 - 00000065 - 101
33 - 0000006C - 108
34 - 0000006C - 108
35 - 0000006F - 111
36 - 0000002C - 44
37 - 00000020 - 32'''
interrupts = '''
on-input 130
'''
log_head = '''
tick=00001 state=FETCH_OPCODE         pc=0001 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- instr_addr=0
tick=00002 state=FETCH_ARGUMENT       pc=0003 ir=CALL    arg=        210 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- CALL 210
tick=00003 state=EXECUTE              pc=00D5 ir=CALL    arg=        210 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- CALL
tick=00004 state=FETCH_OPCODE         pc=00D6 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=213
tick=00005 state=FETCH_ARGUMENT       pc=00DA ir=PUSHI32 arg=          5 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 5
tick=00006 state=EXECUTE              pc=00DA ir=PUSHI32 arg=          5 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00007 state=FETCH_OPCODE         pc=00DB ir=PUSHI32 arg=          0 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=218
tick=00008 state=FETCH_ARGUMENT       pc=00DF ir=PUSHI32 arg=          1 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00009 state=EXECUTE              pc=00DF ir=PUSHI32 arg=          1 tos=          1 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00010 state=FETCH_OPCODE         pc=00E0 ir=STORE   arg=          0 tos=          1 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- instr_addr=223
tick=00011 state=FETCH_ARGUMENT       pc=00E0 ir=STORE   arg=          0 tos=          1 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00012 state=EXECUTE              pc=00E0 ir=STORE   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00013 state=FETCH_OPCODE         pc=00E1 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=224
tick=00014 state=FETCH_ARGUMENT       pc=00E5 ir=PUSHI32 arg=         11 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 11
tick=00015 state=EXECUTE              pc=00E5 ir=PUSHI32 arg=         11 tos=         11 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00016 state=FETCH_OPCODE         pc=00E6 ir=CALL    arg=          0 tos=         11 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=229
tick=00017 state=FETCH_ARGUMENT       pc=00E8 ir=CALL    arg=       -228 tos=         11 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- CALL -228
tick=00018 state=EXECUTE              pc=0004 ir=CALL    arg=       -228 tos=         11 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- CALL
tick=00019 state=FETCH_OPCODE         pc=0005 ir=DUP     arg=          0 tos=         11 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- instr_addr=4
tick=00020 state=FETCH_ARGUMENT       pc=0005 ir=DUP     arg=          0 tos=         11 nos=          0 sp=D000 rp=E001 flags=zncvieint mode=main input=-- DUP
tick=00021 state=EXECUTE              pc=0005 ir=DUP     arg=          0 tos=         11 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- DUP
tick=00022 state=FETCH_OPCODE         pc=0006 ir=LOAD    arg=          0 tos=         11 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=5
tick=00023 state=FETCH_ARGUMENT       pc=0006 ir=LOAD    arg=          0 tos=         11 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- LOAD
tick=00024 state=EXECUTE              pc=0006 ir=LOAD    arg=          0 tos=         18 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- LOAD
tick=00025 state=FETCH_OPCODE         pc=0007 ir=SWAP    arg=          0 tos=         18 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=6
tick=00026 state=FETCH_ARGUMENT       pc=0007 ir=SWAP    arg=          0 tos=         18 nos=         11 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00027 state=EXECUTE              pc=0007 ir=SWAP    arg=          0 tos=         11 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00028 state=FETCH_OPCODE         pc=0008 ir=PUSHI32 arg=          0 tos=         11 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=7
tick=00029 state=FETCH_ARGUMENT       pc=000C ir=PUSHI32 arg=          1 tos=         11 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00030 state=EXECUTE              pc=000C ir=PUSHI32 arg=          1 tos=          1 nos=         11 sp=D002 rp=E001 flags=zncvieint mode=main input=-- PUSHI32
tick=00031 state=FETCH_OPCODE         pc=000D ir=ADD     arg=          0 tos=          1 nos=         11 sp=D002 rp=E001 flags=zncvieint mode=main input=-- instr_addr=12
tick=00032 state=FETCH_ARGUMENT       pc=000D ir=ADD     arg=          0 tos=          1 nos=         11 sp=D002 rp=E001 flags=zncvieint mode=main input=-- ADD
tick=00033 state=EXECUTE              pc=000D ir=ADD     arg=          0 tos=         12 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- ADD
tick=00034 state=FETCH_OPCODE         pc=000E ir=SWAP    arg=          0 tos=         12 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=13
tick=00035 state=FETCH_ARGUMENT       pc=000E ir=SWAP    arg=          0 tos=         12 nos=         18 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00036 state=EXECUTE              pc=000E ir=SWAP    arg=          0 tos=         18 nos=         12 sp=D001 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00037 state=FETCH_OPCODE         pc=000F ir=PUSHI32 arg=          0 tos=         18 nos=         12 sp=D001 rp=E001 flags=zncvieint mode=main input=-- instr_addr=14
tick=00038 state=FETCH_ARGUMENT       pc=0013 ir=PUSHI32 arg=          0 tos=         18 nos=         12 sp=D001 rp=E001 flags=zncvieint mode=main input=-- PUSHI32 0
tick=00039 state=EXECUTE              pc=0013 ir=PUSHI32 arg=          0 tos=          0 nos=         18 sp=D002 rp=E001 flags=zncvieint mode=main input=-- PUSHI32
tick=00040 state=FETCH_OPCODE         pc=0014 ir=OVER    arg=          0 tos=          0 nos=         18 sp=D002 rp=E001 flags=zncvieint mode=main input=-- instr_addr=19
tick=00041 state=FETCH_ARGUMENT       pc=0014 ir=OVER    arg=          0 tos=          0 nos=         18 sp=D002 rp=E001 flags=zncvieint mode=main input=-- OVER
tick=00042 state=EXECUTE              pc=0014 ir=OVER    arg=          0 tos=         18 nos=          0 sp=D003 rp=E001 flags=zncvieint mode=main input=-- OVER
tick=00043 state=FETCH_OPCODE         pc=0015 ir=OVER    arg=          0 tos=         18 nos=          0 sp=D003 rp=E001 flags=zncvieint mode=main input=-- instr_addr=20
tick=00044 state=FETCH_ARGUMENT       pc=0015 ir=OVER    arg=          0 tos=         18 nos=          0 sp=D003 rp=E001 flags=zncvieint mode=main input=-- OVER
tick=00045 state=EXECUTE              pc=0015 ir=OVER    arg=          0 tos=          0 nos=         18 sp=D004 rp=E001 flags=zncvieint mode=main input=-- OVER
tick=00046 state=FETCH_OPCODE         pc=0016 ir=SWAP    arg=          0 tos=          0 nos=         18 sp=D004 rp=E001 flags=zncvieint mode=main input=-- instr_addr=21
tick=00047 state=FETCH_ARGUMENT       pc=0016 ir=SWAP    arg=          0 tos=          0 nos=         18 sp=D004 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00048 state=EXECUTE              pc=0016 ir=SWAP    arg=          0 tos=         18 nos=          0 sp=D004 rp=E001 flags=zncvieint mode=main input=-- SWAP
tick=00049 state=FETCH_OPCODE         pc=0017 ir=LT      arg=          0 tos=         18 nos=          0 sp=D004 rp=E001 flags=zncvieint mode=main input=-- instr_addr=22
tick=00050 state=FETCH_ARGUMENT       pc=0017 ir=LT      arg=          0 tos=         18 nos=          0 sp=D004 rp=E001 flags=zncvieint mode=main input=-- LT
'''
