limit = 10000
log_lines = 35

input = '''
1 A
30 B
60 C
'''

[expected]
stdout = '''
ABC
ticks: 111
'''
code_hex = '''
0 - 20001A - CALL 26
3 - 00 - HALT
4 - 1AFF00 - LOADA 0xFF00
7 - 1BFF02 - STOREA 0xFF02
10 - 2100000001 - PUSHI32 1
15 - 05 - LOAD
16 - 2100000001 - PUSHI32 1
21 - 07 - ADD
22 - 2100000001 - PUSHI32 1
27 - 06 - STORE
28 - 19 - IRET
29 - 17 - EI
30 - 2100000001 - PUSHI32 1
35 - 05 - LOAD
36 - 2100000003 - PUSHI32 3
41 - 0C - EQ
42 - 1FFFF1 - JZ -15
45 - 12 - RET'''
data_hex = '''
0 - 00000000 - 0
1 - 00000000 - 0'''
interrupts = '''
on-input 4
'''
log_head = '''
tick=00001 state=FETCH_OPCODE         pc=0001 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=41 instr_addr=0
tick=00002 state=FETCH_ARGUMENT       pc=0003 ir=CALL    arg=         26 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=41 CALL 26
tick=00003 state=EXECUTE              pc=001D ir=CALL    arg=         26 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=41 CALL
tick=00004 state=FETCH_OPCODE         pc=001E ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=41 instr_addr=29
tick=00005 state=FETCH_ARGUMENT       pc=001E ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=41 EI
tick=00006 state=EXECUTE              pc=001E ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvIEint mode=main input=41 EI
tick=00007 state=INTERRUPT            pc=0004 ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=41 vector=4
tick=00008 state=FETCH_OPCODE         pc=0005 ir=LOADA   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=41 instr_addr=4
tick=00009 state=FETCH_ARGUMENT       pc=0007 ir=LOADA   arg=      65280 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=41 LOADA 0xFF00
tick=00010 state=EXECUTE              pc=0007 ir=LOADA   arg=      65280 tos=         65 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- LOADA
tick=00011 state=FETCH_OPCODE         pc=0008 ir=STOREA  arg=          0 tos=         65 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=7
tick=00012 state=FETCH_ARGUMENT       pc=000A ir=STOREA  arg=      65282 tos=         65 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- STOREA 0xFF02
tick=00013 state=EXECUTE              pc=000A ir=STOREA  arg=      65282 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- STOREA
tick=00014 state=FETCH_OPCODE         pc=000B ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=10
tick=00015 state=FETCH_ARGUMENT       pc=000F ir=PUSHI32 arg=          1 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32 1
tick=00016 state=EXECUTE              pc=000F ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00017 state=FETCH_OPCODE         pc=0010 ir=LOAD    arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=15
tick=00018 state=FETCH_ARGUMENT       pc=0010 ir=LOAD    arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00019 state=EXECUTE              pc=0010 ir=LOAD    arg=          0 tos=          0 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00020 state=FETCH_OPCODE         pc=0011 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=16
tick=00021 state=FETCH_ARGUMENT       pc=0015 ir=PUSHI32 arg=          1 tos=          0 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32 1
tick=00022 state=EXECUTE              pc=0015 ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00023 state=FETCH_OPCODE         pc=0016 ir=ADD     arg=          0 tos=          1 nos=          0 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=21
tick=00024 state=FETCH_ARGUMENT       pc=0016 ir=ADD     arg=          0 tos=          1 nos=          0 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- ADD
tick=00025 state=EXECUTE              pc=0016 ir=ADD     arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- ADD
tick=00026 state=FETCH_OPCODE         pc=0017 ir=PUSHI32 arg=          0 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=22
tick=00027 state=FETCH_ARGUMENT       pc=001B ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32 1
tick=00028 state=EXECUTE              pc=001B ir=PUSHI32 arg=          1 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00029 state=FETCH_OPCODE         pc=001C ir=STORE   arg=          0 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=27
tick=00030 state=FETCH_ARGUMENT       pc=001C ir=STORE   arg=          0 tos=          1 nos=          1 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=42 STORE
tick=00031 state=EXECUTE              pc=001C ir=STORE   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=42 STORE
tick=00032 state=FETCH_OPCODE         pc=001D ir=IRET    arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=42 instr_addr=28
tick=00033 state=FETCH_ARGUMENT       pc=001D ir=IRET    arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=42 IRET
tick=00034 state=EXECUTE              pc=001E ir=IRET    arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvIEint mode=main input=42 IRET
tick=00035 state=INTERRUPT            pc=0004 ir=IRET    arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=42 vector=4
'''
