limit = 10000
log_lines = 25

input = '''
'''

[expected]
stdout = '''
2:12

ticks: 162
'''
code_hex = '''
0 - 200028 - CALL 40
3 - 00 - HALT
4 - 2100000002 - PUSHI32 2
9 - 05 - LOAD
10 - 2100000004 - PUSHI32 4
15 - 05 - LOAD
16 - 07 - ADD
17 - 2100000006 - PUSHI32 6
22 - 06 - STORE
23 - 2100000001 - PUSHI32 1
28 - 05 - LOAD
29 - 2100000003 - PUSHI32 3
34 - 05 - LOAD
35 - 07 - ADD
36 - 2100000005 - PUSHI32 5
41 - 06 - STORE
42 - 12 - RET
43 - 2100000001 - PUSHI32 1
48 - 2100000001 - PUSHI32 1
53 - 06 - STORE
54 - 2100000005 - PUSHI32 5
59 - 2100000002 - PUSHI32 2
64 - 06 - STORE
65 - 2100000001 - PUSHI32 1
70 - 2100000003 - PUSHI32 3
75 - 06 - STORE
76 - 2100000007 - PUSHI32 7
81 - 2100000004 - PUSHI32 4
86 - 06 - STORE
87 - 20FFAA - CALL -86
90 - 2100000005 - PUSHI32 5
95 - 05 - LOAD
96 - 2100000030 - PUSHI32 48
101 - 07 - ADD
102 - 1BFF02 - STOREA 0xFF02
105 - 210000003A - PUSHI32 58
110 - 1BFF02 - STOREA 0xFF02
113 - 2100000006 - PUSHI32 6
118 - 05 - LOAD
119 - 210000000A - PUSHI32 10
124 - 0A - DIV
125 - 2100000030 - PUSHI32 48
130 - 07 - ADD
131 - 1BFF02 - STOREA 0xFF02
134 - 2100000006 - PUSHI32 6
139 - 05 - LOAD
140 - 210000000A - PUSHI32 10
145 - 0B - MOD
146 - 2100000030 - PUSHI32 48
151 - 07 - ADD
152 - 1BFF02 - STOREA 0xFF02
155 - 210000000A - PUSHI32 10
160 - 1BFF02 - STOREA 0xFF02
163 - 12 - RET'''
data_hex = '''
0 - 00000000 - 0
1 - 00000000 - 0
2 - 00000000 - 0
3 - 00000000 - 0
4 - 00000000 - 0
5 - 00000000 - 0
6 - 00000000 - 0'''
interrupts = '''
'''
log_head = '''
tick=00001 state=FETCH_OPCODE         pc=0001 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- instr_addr=0
tick=00002 state=FETCH_ARGUMENT       pc=0003 ir=CALL    arg=         40 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=-- CALL 40
tick=00003 state=EXECUTE              pc=002B ir=CALL    arg=         40 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- CALL
tick=00004 state=FETCH_OPCODE         pc=002C ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=43
tick=00005 state=FETCH_ARGUMENT       pc=0030 ir=PUSHI32 arg=          1 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00006 state=EXECUTE              pc=0030 ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00007 state=FETCH_OPCODE         pc=0031 ir=PUSHI32 arg=          0 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=48
tick=00008 state=FETCH_ARGUMENT       pc=0035 ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00009 state=EXECUTE              pc=0035 ir=PUSHI32 arg=          1 tos=          1 nos=          1 sp=D001 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00010 state=FETCH_OPCODE         pc=0036 ir=STORE   arg=          0 tos=          1 nos=          1 sp=D001 rp=E000 flags=zncvieint mode=main input=-- instr_addr=53
tick=00011 state=FETCH_ARGUMENT       pc=0036 ir=STORE   arg=          0 tos=          1 nos=          1 sp=D001 rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00012 state=EXECUTE              pc=0036 ir=STORE   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00013 state=FETCH_OPCODE         pc=0037 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=54
tick=00014 state=FETCH_ARGUMENT       pc=003B ir=PUSHI32 arg=          5 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 5
tick=00015 state=EXECUTE              pc=003B ir=PUSHI32 arg=          5 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00016 state=FETCH_OPCODE         pc=003C ir=PUSHI32 arg=          0 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=59
tick=00017 state=FETCH_ARGUMENT       pc=0040 ir=PUSHI32 arg=          2 tos=          5 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32 2
tick=00018 state=EXECUTE              pc=0040 ir=PUSHI32 arg=          2 tos=          2 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00019 state=FETCH_OPCODE         pc=0041 ir=STORE   arg=          0 tos=          2 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- instr_addr=64
tick=00020 state=FETCH_ARGUMENT       pc=0041 ir=STORE   arg=          0 tos=          2 nos=          5 sp=D001 rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00021 state=EXECUTE              pc=0041 ir=STORE   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- STORE
tick=00022 state=FETCH_OPCODE         pc=0042 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- instr_addr=65
tick=00023 state=FETCH_ARGUMENT       pc=0046 ir=PUSHI32 arg=          1 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=-- PUSHI32 1
tick=00024 state=EXECUTE              pc=0046 ir=PUSHI32 arg=          1 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- PUSHI32
tick=00025 state=FETCH_OPCODE         pc=0047 ir=PUSHI32 arg=          0 tos=          1 nos=          0 sp=D000 rp=E000 flags=zncvieint mode=main input=-- instr_addr=70
'''
