limit = 5000
log_lines = 50

input = '''
1 3
40 1
80 2
'''

[expected]
stdout = '''
1 2 3

ticks: 462
'''
code_hex = '''
0 - 2000FB - CALL 251
3 - 00 - HALT
4 - 2100000005 - PUSHI32 5
9 - 05 - LOAD
10 - 2100000030 - PUSHI32 48
15 - 08 - SUB
16 - 2100000004 - PUSHI32 4
21 - 05 - LOAD
22 - 2100000000 - PUSHI32 0
27 - 0C - EQ
28 - 1F0009 - JZ 9
31 - 2100000001 - PUSHI32 1
36 - 06 - STORE
37 - 1E001E - JMP 30
40 - 2100000004 - PUSHI32 4
45 - 05 - LOAD
46 - 2100000001 - PUSHI32 1
51 - 0C - EQ
52 - 1F0009 - JZ 9
55 - 2100000002 - PUSHI32 2
60 - 06 - STORE
61 - 1E0006 - JMP 6
64 - 2100000003 - PUSHI32 3
69 - 06 - STORE
70 - 2100000004 - PUSHI32 4
75 - 05 - LOAD
76 - 2100000001 - PUSHI32 1
81 - 07 - ADD
82 - 2100000004 - PUSHI32 4
87 - 06 - STORE
88 - 12 - RET
89 - 1AFF00 - LOADA 0xFF00
92 - 2100000005 - PUSHI32 5
97 - 06 - STORE
98 - 20FF9F - CALL -97
101 - 19 - IRET
102 - 2100000001 - PUSHI32 1
107 - 05 - LOAD
108 - 2100000002 - PUSHI32 2
113 - 05 - LOAD
114 - 0E - GT
115 - 1F0018 - JZ 24
118 - 2100000001 - PUSHI32 1
123 - 05 - LOAD
124 - 2100000002 - PUSHI32 2
129 - 05 - LOAD
130 - 2100000001 - PUSHI32 1
135 - 06 - STORE
136 - 2100000002 - PUSHI32 2
141 - 06 - STORE
142 - 12 - RET
143 - 2100000002 - PUSHI32 2
148 - 05 - LOAD
149 - 2100000003 - PUSHI32 3
154 - 05 - LOAD
155 - 0E - GT
156 - 1F0018 - JZ 24
159 - 2100000002 - PUSHI32 2
164 - 05 - LOAD
165 - 2100000003 - PUSHI32 3
170 - 05 - LOAD
171 - 2100000002 - PUSHI32 2
176 - 06 - STORE
177 - 2100000003 - PUSHI32 3
182 - 06 - STORE
183 - 12 - RET
184 - 2100000001 - PUSHI32 1
189 - 05 - LOAD
190 - 2100000030 - PUSHI32 48
195 - 07 - ADD
196 - 1BFF02 - STOREA 0xFF02
199 - 2100000020 - PUSHI32 32
204 - 1BFF02 - STOREA 0xFF02
207 - 2100000002 - PUSHI32 2
212 - 05 - LOAD
213 - 2100000030 - PUSHI32 48
218 - 07 - ADD
219 - 1BFF02 - STOREA 0xFF02
222 - 2100000020 - PUSHI32 32
227 - 1BFF02 - STOREA 0xFF02
230 - 2100000003 - PUSHI32 3
235 - 05 - LOAD
236 - 2100000030 - PUSHI32 48
241 - 07 - ADD
242 - 1BFF02 - STOREA 0xFF02
245 - 210000000A - PUSHI32 10
250 - 1BFF02 - STOREA 0xFF02
253 - 12 - RET
254 - 17 - EI
255 - 2100000004 - PUSHI32 4
260 - 05 - LOAD
261 - 2100000003 - PUSHI32 3
266 - 0C - EQ
267 - 1FFFF1 - JZ -15
270 - 20FF55 - CALL -171
273 - 20FF7B - CALL -133
276 - 20FF4F - CALL -177
279 - 20FF9E - CALL -98
282 - 12 - RET'''
data_hex = '''
0 - 00000000 - 0
1 - 00000000 - 0
2 - 00000000 - 0
3 - 00000000 - 0
4 - 00000000 - 0
5 - 00000000 - 0'''
interrupts = '''
on-input 89
'''
log_head = '''
tick=00001 state=FETCH_OPCODE         pc=0001 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=33 instr_addr=0
tick=00002 state=FETCH_ARGUMENT       pc=0003 ir=CALL    arg=        251 tos=          0 nos=          0 sp=CFFF rp=DFFF flags=zncvieint mode=main input=33 CALL 251
tick=00003 state=EXECUTE              pc=00FE ir=CALL    arg=        251 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=33 CALL
tick=00004 state=FETCH_OPCODE         pc=00FF ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=33 instr_addr=254
tick=00005 state=FETCH_ARGUMENT       pc=00FF ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvieint mode=main input=33 EI
tick=00006 state=EXECUTE              pc=00FF ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E000 flags=zncvIEint mode=main input=33 EI
tick=00007 state=INTERRUPT            pc=0059 ir=EI      arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=33 vector=89
tick=00008 state=FETCH_OPCODE         pc=005A ir=LOADA   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=33 instr_addr=89
tick=00009 state=FETCH_ARGUMENT       pc=005C ir=LOADA   arg=      65280 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=33 LOADA 0xFF00
tick=00010 state=EXECUTE              pc=005C ir=LOADA   arg=      65280 tos=         51 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- LOADA
tick=00011 state=FETCH_OPCODE         pc=005D ir=PUSHI32 arg=          0 tos=         51 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=92
tick=00012 state=FETCH_ARGUMENT       pc=0061 ir=PUSHI32 arg=          5 tos=         51 nos=          0 sp=D000 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32 5
tick=00013 state=EXECUTE              pc=0061 ir=PUSHI32 arg=          5 tos=          5 nos=         51 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00014 state=FETCH_OPCODE         pc=0062 ir=STORE   arg=          0 tos=          5 nos=         51 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=97
tick=00015 state=FETCH_ARGUMENT       pc=0062 ir=STORE   arg=          0 tos=          5 nos=         51 sp=D001 rp=E001 flags=zncvIEINT mode=interrupt input=-- STORE
tick=00016 state=EXECUTE              pc=0062 ir=STORE   arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- STORE
tick=00017 state=FETCH_OPCODE         pc=0063 ir=CALL    arg=          0 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- instr_addr=98
tick=00018 state=FETCH_ARGUMENT       pc=0065 ir=CALL    arg=        -97 tos=          0 nos=          0 sp=CFFF rp=E001 flags=zncvIEINT mode=interrupt input=-- CALL -97
tick=00019 state=EXECUTE              pc=0004 ir=CALL    arg=        -97 tos=          0 nos=          0 sp=CFFF rp=E002 flags=zncvIEINT mode=interrupt input=-- CALL
tick=00020 state=FETCH_OPCODE         pc=0005 ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=CFFF rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=4
tick=00021 state=FETCH_ARGUMENT       pc=0009 ir=PUSHI32 arg=          5 tos=          0 nos=          0 sp=CFFF rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32 5
tick=00022 state=EXECUTE              pc=0009 ir=PUSHI32 arg=          5 tos=          5 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00023 state=FETCH_OPCODE         pc=000A ir=LOAD    arg=          0 tos=          5 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=9
tick=00024 state=FETCH_ARGUMENT       pc=000A ir=LOAD    arg=          0 tos=          5 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00025 state=EXECUTE              pc=000A ir=LOAD    arg=          0 tos=         51 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00026 state=FETCH_OPCODE         pc=000B ir=PUSHI32 arg=          0 tos=         51 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=10
tick=00027 state=FETCH_ARGUMENT       pc=000F ir=PUSHI32 arg=         48 tos=         51 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32 48
tick=00028 state=EXECUTE              pc=000F ir=PUSHI32 arg=         48 tos=         48 nos=         51 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00029 state=FETCH_OPCODE         pc=0010 ir=SUB     arg=          0 tos=         48 nos=         51 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=15
tick=00030 state=FETCH_ARGUMENT       pc=0010 ir=SUB     arg=          0 tos=         48 nos=         51 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- SUB
tick=00031 state=EXECUTE              pc=0010 ir=SUB     arg=          0 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- SUB
tick=00032 state=FETCH_OPCODE         pc=0011 ir=PUSHI32 arg=          0 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=16
tick=00033 state=FETCH_ARGUMENT       pc=0015 ir=PUSHI32 arg=          4 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32 4
tick=00034 state=EXECUTE              pc=0015 ir=PUSHI32 arg=          4 tos=          4 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32
tick=00035 state=FETCH_OPCODE         pc=0016 ir=LOAD    arg=          0 tos=          4 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=21
tick=00036 state=FETCH_ARGUMENT       pc=0016 ir=LOAD    arg=          0 tos=          4 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00037 state=EXECUTE              pc=0016 ir=LOAD    arg=          0 tos=          0 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- LOAD
tick=00038 state=FETCH_OPCODE         pc=0017 ir=PUSHI32 arg=          0 tos=          0 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- instr_addr=22
tick=00039 state=FETCH_ARGUMENT       pc=001B ir=PUSHI32 arg=          0 tos=          0 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=-- PUSHI32 0
tick=00040 state=EXECUTE              pc=001B ir=PUSHI32 arg=          0 tos=          0 nos=          0 sp=D002 rp=E002 flags=zncvIEINT mode=interrupt input=31 PUSHI32
tick=00041 state=FETCH_OPCODE         pc=001C ir=EQ      arg=          0 tos=          0 nos=          0 sp=D002 rp=E002 flags=zncvIEINT mode=interrupt input=31 instr_addr=27
tick=00042 state=FETCH_ARGUMENT       pc=001C ir=EQ      arg=          0 tos=          0 nos=          0 sp=D002 rp=E002 flags=zncvIEINT mode=interrupt input=31 EQ
tick=00043 state=EXECUTE              pc=001C ir=EQ      arg=          0 tos=          1 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=31 EQ
tick=00044 state=FETCH_OPCODE         pc=001D ir=JZ      arg=          0 tos=          1 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=31 instr_addr=28
tick=00045 state=FETCH_ARGUMENT       pc=001F ir=JZ      arg=          9 tos=          1 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=31 JZ 9
tick=00046 state=EXECUTE              pc=001F ir=JZ      arg=          9 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=31 JZ flag=1
tick=00047 state=FETCH_OPCODE         pc=0020 ir=PUSHI32 arg=          0 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=31 instr_addr=31
tick=00048 state=FETCH_ARGUMENT       pc=0024 ir=PUSHI32 arg=          1 tos=          3 nos=          0 sp=D000 rp=E002 flags=zncvIEINT mode=interrupt input=31 PUSHI32 1
tick=00049 state=EXECUTE              pc=0024 ir=PUSHI32 arg=          1 tos=          1 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=31 PUSHI32
tick=00050 state=FETCH_OPCODE         pc=0025 ir=STORE   arg=          0 tos=          1 nos=          3 sp=D001 rp=E002 flags=zncvIEINT mode=interrupt input=31 instr_addr=36
'''
